In [227]:
import pandas as pd

In [228]:
df=pd.read_csv(r"C:\Users\Chaitanya\Downloads\train (1).csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [196]:
df.drop(['Name','Cabin','Ticket','Fare','PassengerId'],axis=1,inplace=True)

In [ ]:
df

In [197]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Embarked      2
dtype: int64

In [198]:
df=df.bfill().ffill()

In [199]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Embarked    0
dtype: int64

In [200]:
from sklearn.preprocessing import LabelEncoder

In [201]:
from sklearn.preprocessing import LabelEncoder
les = LabelEncoder()
lee = LabelEncoder()
df['Sex'] = les.fit_transform(df['Sex'])
df['Embarked'] = lee.fit_transform(df['Embarked'])

In [202]:
x=df.iloc[:,1:]
y=df["Survived"]

In [203]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [204]:
from sklearn.linear_model import LogisticRegression

In [205]:
model=LogisticRegression()

In [206]:
model.fit(xtrain,ytrain)

LogisticRegression()

In [207]:
yp=model.predict(xtest)

In [208]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,yp)

0.7932960893854749

In [209]:
df

     Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0           0       3    1  22.0      1      0         2
1           1       1    0  38.0      1      0         0
2           1       3    0  26.0      0      0         2
3           1       1    0  35.0      1      0         2
4           0       3    1  35.0      0      0         2
..        ...     ...  ...   ...    ...    ...       ...
886         0       2    1  27.0      0      0         2
887         1       1    0  19.0      0      0         2
888         0       3    0  26.0      1      2         2
889         1       1    1  26.0      0      0         0
890         0       3    1  32.0      0      0         1

[891 rows x 7 columns]

In [210]:
x

     Pclass  Sex   Age  SibSp  Parch  Embarked
0         3    1  22.0      1      0         2
1         1    0  38.0      1      0         0
2         3    0  26.0      0      0         2
3         1    0  35.0      1      0         2
4         3    1  35.0      0      0         2
..      ...  ...   ...    ...    ...       ...
886       2    1  27.0      0      0         2
887       1    0  19.0      0      0         2
888       3    0  26.0      1      2         2
889       1    1  26.0      0      0         0
890       3    1  32.0      0      0         1

[891 rows x 6 columns]

In [211]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [229]:
df1=pd.read_csv(r"C:\Users\Chaitanya\Downloads\test.csv")
pid=df1['PassengerId']

In [230]:
df1.drop(['Name','Cabin','Ticket','Fare','PassengerId'],axis=1,inplace=True)

In [231]:
df1.isnull().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Embarked     0
dtype: int64

In [232]:
df1=df1.bfill().ffill()

In [233]:
df1.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Embarked    0
dtype: int64

In [234]:
from sklearn.preprocessing import LabelEncoder
les = LabelEncoder()
lee = LabelEncoder()
df1['Sex'] = les.fit_transform(df1['Sex'])
df1['Embarked'] = lee.fit_transform(df1['Embarked'])

In [235]:
from sklearn.linear_model import LogisticRegression

In [236]:
model1=LogisticRegression()
model1.fit(xtrain,ytrain)

LogisticRegression()

In [247]:
yp1=model.predict(df1)

In [248]:
yp1

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [249]:
pid

0       892
1       893
2       894
3       895
4       896
       ...
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, Length: 418, dtype: int64

In [250]:
mobile=pd.concat([pid,pd.DataFrame(yp1)],axis=1)

In [251]:
mobile.columns=['PassengerId','Survived']

In [253]:
mobile.to_csv('C:survival1.csv',index=False)